### ISSUE TITLE
Composer Dependency Hell

### ISSUE THREAD

**Issue by Seldaek** [ramsey/composer-repl#3]
OK I had a look at the repro case from https://github.com/ramsey/composer-plugin-issue 

The root cause of the problem really is https://github.com/ramsey/composer-repl/blob/91e0403b4695d299e7c37c53e6776efa940fe651/src/Composer/ReplCommand.php#L86 which prepends the application's autoloader to Composer's, which mean that some of the files get loaded from the Composer phar and then whatever is loaded after this line runs is loaded from the local vendor dir.

A workaround is to make sure everything which may clash gets loaded beforehand, e.g this appears to resolve it:

```
        class_exists('Symfony\Component\Console\Input\ArrayInput');

        /** @psalm-suppress UnresolvableInclude */
        require $vendorDir . '/autoload.php';
```

The only proper and definitive fix however would be to stop sharing the process space between the project deps and Composer.. And for that having a binary like `vendor/bin/composer-repl` or whatever you wanna call it which does locate the vendor dir, include autoloader, do whatever is needed, then start psysh, would be more appropriate.

You could even run `vendor/bin/composer-repl` as a new process (make sure to run with TTY enabled) from within the ReplCommand so that you retain BC and retain a way to call this via `composer repl`. But people could also add `"scripts": {"repl": "@php vendor/bin/composer-repl"}` and be able to call `composer repl` then which would run the composer-repl binary.. and that would not require a composer plugin or command integration here.

If any of the above is unclear please ask I'm happy to explain in more details.

**Comment by Lewiscowles1986** [comment]
Won't this "resolve" the bug by loading the non-vendored non-plugin specific Symfony console?

**Comment by Seldaek** [comment]
Yes as I said that's a workaround, it fixes the current symptom but not the underlying problem.

**Comment by Lewiscowles1986** [comment]
Just wanted to understand. Can confirm this is working for me from PHP 8 & 8.1 Nice 👍

**Comment by Seldaek** [comment]
Replying to https://github.com/ramsey/composer-plugin-issue/issues/1 here just to keep everything in the same place, as it really expands on my answer above.

In Composer we cannot run plugins in a sub-process IMO, as they would still need access to the runtime Composer stuff, which would mean loading the Composer classes (and dependencies) again. So there's no point.

It's indeed a problem of the sequence of autoloaders, and that is why in Composer we run the Composer autoloader first by default, and run plugin/script dependencies autoloaders (which are created at runtime, and not loaded from vendor/autoload.php) *after* the Composer one, as they get appended.

The default for the vendor/autoload.php autoloader though is to prepend itself when registering, which was done to fix issues in contexts like PHPUnit where PHPUnit loads the bootstrap file and then the application loader should take precedence over PHPUnit, otherwise you may get broken tests. But it's also true that if PHPUnit uses the same dependencies as your app in a version which is incompatible you may break PHPUnit this way.. it does have the same dilemma as Composer in terms of minimizing third-party dependencies, and you can see that it also hardly uses any.

So another workaround would be to load the application autoloader in append mode vs prepend.. which could be done as is I believe:

```php
        /** @psalm-suppress UnresolvableInclude */
        $loader = require $vendorDir . '/autoload.php';
        $loader->unregister();
        $loader->register(false);
```

That would also fix the symptom but it doesn't really isolate things so it may still result in issues down the line. Process isolation in the context of composer-repl is IMO possible and would be beneficial and fix things in a more definitive way.

**Comment by ramsey** [comment]
I'm proceeding with a solution that runs the existing `bin/repl` in a separate process. It works well; I'm working out some issues with tests before pushing up the code.

**Comment by ramsey** [comment]
Thanks for the thorough investigation and recommendations, @Seldaek!

I've modified the `composer repl` command so that it now executes `bin/repl` in a separate process: https://github.com/ramsey/composer-repl-lib/blob/0732a3cf0e63f56cf29f97ef36fd61f37c333b86/src/Composer/ReplCommand.php#L76-L84

I've also moved all the "library" code out of this repository into [ramsey/composer-repl-lib](https://github.com/ramsey/composer-repl-lib). This will allow others to install the package as a non-plugin, and it will also allow for easier extension and building on top of it.

This repository is now just the plugin configuration, and it requires ramsey/composer-repl-lib.

**Comment by Lewiscowles1986** [comment]
Thank you both for your valuable insight. Sorry that I cannot think of a more appropriate venue, and apologies for posting on a now closed issue; I wanted to add some context to the follow-up I got.

### Sub-processing

> In Composer we cannot run plugins in a sub-process IMO, as they would still need access to the runtime Composer stuff, which would mean loading the Composer classes (and dependencies) again. So there's no point.

a. I Hear you. I think perhaps we were talking about two separate things. I was saying for Ben specific repl plugin; I think sub-processing is a tool, that could get fast-feedback, and allow a repl to be run as a composer plugin; that uses composer dependencies; but loads a sub-process which runs a repl session. Not that composer itself needs to or should have been designed in any other way.

Again, for Ben project; this could then be sent details from the parent process; and use the source code for the project it is installed under separately. It was a castaway thought for ways to avoid the context switch cost of registering and unregistering autoloaders; as well as attempting some class isolation; which might be a more "correct/strict" (struggling for words here), but painful way to keep two things separate under a single process. This (to my mind) is very similar to iterative vs recursive solving an algorithm.

b. More generally to composer; I'm not 100% certain that there is no way to make subprocessing work; and can even think of sandboxing benefits; but I'll accept that it's a direction that has more decisions that would have to be made about reading and issuing commands to change the internal state of the parent composer process. To do that for a single use case, I agree would not be good.

Further on that. I wonder if you'd considered a potential work-around for this without requiring composer autoloader in the subprocess? Using shared memory or a dedicated IO handle for communication are some methods. I'll not suggest a socket based server 😄. I'll hand wave this off as "standard IPC applies"; but I also agree that reaching for IPC if it can be avoided is a smell, and that it could be a lot of work. So not a proposal, more of a "I wonder if they considered?".

I'm ecstatic Ben has chosen to explore the sub-process route for their specific plugin.

### Unregistering / boundary enforcement

The largest issue I see here I alluded to, perhaps too vaguely. I Apologize for that vagueness:

> One issue is that it is a race to define the classes used; even with unregistering; there would be yet more work to clean off things more within the same PHP instance.

I think we were agreeing when you wrote:

> So another workaround would be to load the application autoloader in append mode vs prepend.. which could be done as is I believe:
>
>         /** @psalm-suppress UnresolvableInclude */
>         $loader = require $vendorDir . '/autoload.php';
>         $loader->unregister();
>         $loader->register(false);
>
> That would also fix the symptom but it doesn't really isolate things so it may still result in issues down the line. Process isolation in the context of composer-repl is IMO possible and would be beneficial and fix things in a more definitive way.

The part this example didn't address which I was hinting at and I think you were saying makes this "unsolvable" was that once a class is used; it won't matter if a different autoloader is present because it will have a class definition from a prior library version dependency tree. 

Worse still, it may not have the entire tree of dependent classes; or load an incompatible as-yet unloaded instance of a class with the correct namespace and class name, but an incompatible version from another sub-tree. The two autoloaders becomes like having two box-office directors for a film; each unable to compromise. This was not lost on me.

Thanks for chat; glad Ben has a direction now, and that it's not involved sweeping changes to core infrastructure or tooling. If solving or exploring the composer is of interest; I'd be at least curious to look 👀 or participate 💬 📜 💻 .
